image: rustlang/rust:nightly

stages:
  - test

variables:
  CARGO_HOME: $CI_PROJECT_DIR/.cargo

cache:
  key: test-cache
  paths:
    - .cargo/
    - target/

test:
  stage: test
  only:
    - develop
  script:
    - cargo test --verbose
  allow_failure: false
# TODO: consider test for master branch
