image: rustlang/rust:nightly

stages:
  - test
  # - package

variables:
  CARGO_HOME: $CI_PROJECT_DIR/.cargo

cache:
  key: test-cache
  paths:
    - .cargo/
    - target/

test:
  stage: test
  script:
    - cargo test --verbose
  allow_failure: false

# TODO: Setup crates.io account & stuff.
# package:
  # rules:
    # - if: '$CI_COMMIT_BRANCH == "master"'
      # when: on_success
  # script:
    # - cargo package
