image: rustlang/rust:nightly

stages:
  - test
  - docs

variables:
  CARGO_HOME: $CI_PROJECT_DIR/.cargo

cache:
  key: test-cache
  paths:
    - .cargo/
    - target/
test:
  stage: test
  only:
    - develop
  script:
    - cargo test --verbose
  allow_failure: false
# IDEA: run tests on master

docs:
  stage: docs
  only:
    - master
  script:
    - cargo doc --release --verbose
  allow_failure: false
