[package]
name = "ignore"
version = "1.1.3"
authors = ["fisherprime <mbock.ernie40@gmail.com>"]
description = "A .gitignore file generator."
edition = "2018"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.10"
clap = "2.33.0"
dirs = "2.0.2"
fern = "0.5.9"
git2 = "0.10.2"
log = "0.4.8"
serde = { version = "1.0.103", features = ["derive"] }
toml = "0.5.6"
