[package]
name = "ignore-ng"
version = "0.1.0"
authors = ["fisherprime <mbock.ernie40@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# nom = "5.0.1"
# libgit2-sys
# url
chrono = "0.4.9"
clap = "2.33.0"
serde = { version = "1.0.101", features = ["derive"] }
dirs = "2.0.2"
fern = "0.5.8"
git2 = "0.10.1"
log = "0.4.8"
regex = "1.3.1"
toml = "0.5.3"
