[package]
name = "ignore-ng"
version = "0.1.0"
authors = ["fisherprime <mbock.ernie40@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.9"
clap = "2.33.0"
fern = "0.5.8"
log = "0.4.8"
